Gemfile, README.md, Rakefile, lib/stream-chat.rb, lib/stream-chat/channel.rb, lib/stream-chat/client.rb, lib/stream-chat/errors.rb, lib/stream-chat/version.rb, spec/channel_spec.rb, spec/client_spec.rb, stream-chat.gemspec
First release of the ruby chat SDK
=> First release

README.md, lib/stream-chat/channel.rb, lib/stream-chat/client.rb, lib/stream-chat/version.rb, spec/client_spec.rb
=> Add more examples to README.md

lib/stream-chat/channel.rb, lib/stream-chat/client.rb, lib/stream-chat/version.rb
=> Check webhook signature with secret

lib/stream-chat/channel.rb, lib/stream-chat/client.rb, spec/channel_spec.rb, spec/client_spec.rb
=> Add missing SDK methods

CHANGELOG.md, lib/stream-chat/version.rb, stream-chat.gemspec
Fixes https://github.com/GetStream/stream-chat-ruby/issues/8
=> Mark gems use for testing as development dependencies

CHANGELOG.md, lib/stream-chat/channel.rb, spec/channel_spec.rb
=> support invites after channel creation

lib/stream-chat/client.rb
Solves #11 
Just fix for issue without breaking changes
=> Fix for update users ID in key

lib/stream-chat/errors.rb
=> Fix error parsing

CHANGELOG.md, lib/stream-chat/version.rb
=> Release 1.1.2

.gitignore, .travis.yml, lib/stream-chat/client.rb, spec/client_spec.rb
* Add 2.7 to travis
* Ignore lock
=> Fix params for delete user

lib/stream-chat/client.rb, spec/client_spec.rb
=> Improve blocklist tests for parallel run

README.md, lib/stream-chat/client.rb, spec/client_spec.rb
=> Add export channel support

lib/stream-chat/client.rb
=> Use helper for sort conversion

lib/stream-chat/client.rb
=> Use post for query channels

lib/stream-chat/channel.rb, lib/stream-chat/client.rb
Refactor when there is no need to use string and a symbol suffices.
=> Improve symbol conversions

.github/workflows/ci.yml, spec/client_spec.rb
Multi version running is causing tests to fail if app config is changing.
=> Run tests in one version if depends on app config

README.md, lib/stream-chat/channel.rb
=> Increase convenience of query members

README.md, lib/stream-chat/channel.rb, spec/channel_spec.rb
=> Add update channel partial

.github/workflows/ci.yml, spec/channel_spec.rb, spec/client_spec.rb
=> Add ruby 3

.github/workflows/ci.yml, spec/client_spec.rb
=> Use max parallel to run all tests

lib/stream-chat/client.rb
Added token revocation helper methods
- `revoke_tokens()`
- `revoke_user_token()`
- `revoke_users_token()`
Add `iat` claim in payload while generating jwt token
=> Add token revocation methods

lib/stream-chat/client.rb, spec/client_spec.rb
=> Add custom command support

lib/stream-chat/client.rb, spec/client_spec.rb
=> Feature: Search endpoint improvements

lib/stream-chat/channel.rb
=> Fix StreamChannelException raises.

.github/workflows/ci.yml, lib/stream-chat/client.rb, spec/client_spec.rb
- Fix channel export test
- Fix rubocop warning
- Replace actions/setup-ruby@v1 with ruby/setup-ruby@v1 Github Action
=> Fix minor issues

lib/stream-chat/client.rb, spec/client_spec.rb, stream-chat.gemspec
Added :
shadow_ban
remove_shadow_ban
update_message_partial
pin_message
unpin_message methods
=> [CHAT-2598] Add shadow_ban, remove_shadow_ban, update_message_partial, pin_message & unpin_message methods

lib/stream-chat/channel.rb, spec/channel_spec.rb
Allow to pass options for truncate channel action
=> Add options to truncation

.github/workflows/ci.yml, lib/stream-chat/channel.rb, lib/stream-chat/client.rb, spec/channel_spec.rb, spec/client_spec.rb
=> Permissionsv2

.gitignore, lib/stream-chat/channel.rb, spec/channel_spec.rb
Add options to add members, such as hide_history
=> feat: add options to add members

.github/workflows/ci.yml, .github/workflows/initiate_release.yml, .github/workflows/release.yml, .gitignore, .rubocop.yml, .versionrc.js, CHANGELOG.md, Gemfile, README.md, lib/stream-chat/client.rb, scripts/get_changelog_diff.js, stream-chat.gemspec
Automated release flow
Note: needed to turn off 2FA because its an automated flow
=> ci: add release flow

.github/workflows/ci.yml, README.md, lib/stream-chat/channel.rb, lib/stream-chat/client.rb, spec/channel_spec.rb, spec/client_spec.rb
=> feat: full feature parity

lib/stream-chat/client.rb, stream-chat.gemspec
- Add connection pooling and set an idle timeout
=> feat: add connection pooling and idle timeout

lib/stream-chat/client.rb, spec/client_spec.rb
=> refactor: env var handling enhancement

lib/stream-chat/channel.rb, spec/channel_spec.rb
add helper for invitation acceptance and rejection
=> feat: add helper for invitation acceptance and rejection

lib/stream-chat/client.rb, spec/client_spec.rb
=> fix: update app settings

lib/stream-chat/client.rb
=> feat: add push provider apis

lib/stream-chat/client.rb
=> feat: add new device field

.github/workflows/ci.yml, Gemfile, spec/channel_spec.rb, spec/client_spec.rb, spec/spec_helper.rb, stream-chat.gemspec
Print code coverage into the console
=> ci: print test coverage during build

lib/stream-chat/channel.rb, lib/stream-chat/client.rb, lib/stream-chat/errors.rb, lib/stream-chat/stream_rate_limits.rb, lib/stream-chat/stream_response.rb, lib/stream-chat/types.rb, lib/stream-chat/util.rb
Fixing https://github.com/GetStream/stream-chat-ruby/issues/97
=> fix(sorbet): turn off runtime checks properly

.github/workflows/ci.yml, .github/workflows/initiate_release.yml, .github/workflows/release.yml, .github/workflows/scheduled_test.yml
=> chore: add scheduled test

spec/channel_spec.rb, spec/client_spec.rb
=> test: cleanup tests

lib/stream-chat/channel.rb, lib/stream-chat/client.rb, lib/stream-chat/errors.rb, lib/stream-chat/stream_rate_limits.rb, lib/stream-chat/stream_response.rb, lib/stream-chat/types.rb, lib/stream-chat/util.rb, spec/client_spec.rb
=> feat(sorbet)!: enable runtime typecheck

Gemfile, lib/stream-chat/client.rb, stream-chat.gemspec
=> feat: commit message endpoint

CONTRIBUTING.md, lib/stream-chat/channel.rb, spec/client_spec.rb
Fixes: https://getstream.slack.com/archives/CRJ5X7WDD/p1689103708732979
Reference: https://sorbet.org/docs/sigs#rest-parameters
=> [PBE-852] fix: sorbet type for mark_read function signature

lib/stream-chat/client.rb, spec/client_spec.rb
=> feat: add check sns point

lib/stream-chat/client.rb
=> enable restore a single or multiple users functionality

.github/workflows/ci.yml, lib/stream-chat/channel.rb, spec/channel_spec.rb, spec/client_spec.rb
https://linear.app/stream/issue/CHA-17/members-custom-data-ruby-sdk
=> [CHA-17] - added support for pinning, archiving and partial member update
